Update 0-functions.yaml

diff --git a/.github/workflows/0-functions.yaml b/.github/workflows/0-functions.yaml
--- a/.github/workflows/0-functions.yaml
+++ b/.github/workflows/0-functions.yaml
@@ -25,10 +25,11 @@ jobs:
       - name: Bug step
         if: ${{ failure() && !cancelled() && contains(github.event.pull_request.title, 'fix') }}
         run: echo "I am a bug fix"
-      - name: Failing step
-        run: |
-          sleep 20
-          exit 1
+        
+      # - name: Failing step
+      #   run: |
+      #     sleep 20
+      #     exit 1
 
       # - name: I will be skipped
       #   if: ${{ success() }}
