Update 00-functions.yaml

diff --git a/.github/workflows/00-functions.yaml b/.github/workflows/00-functions.yaml
--- a/.github/workflows/00-functions.yaml
+++ b/.github/workflows/00-functions.yaml
@@ -1,8 +1,11 @@
 name: 00 - Using Functions
 
 on:
-  push:
-    branches: [ "main" ]
+  # push:
+  #   branches: [ "main" ]
+  pull_request:
+    branches: ["main"]
+    
   workflow_dispatch:
 
 jobs:
@@ -10,23 +13,41 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Failing step
-        run: |
-          sleep 20
-          exit 1
+      - name: Print PR title
+        if: ${{ github.event_name == 'pull_request' }}
+        run: echo "PR title =  ${{ github.event.pull_request_title }}"
 
-      - name: I will be skipped
-        if: ${{ success() }}
-        run: echo "I will print if previous steps succeed."
+      - name: Print PR labels 
+        if: ${{ github.event_name == 'pull_request' }}
+        run: echo "PR labels = ${{ toJson(github.event.pull_request.labels }}"
 
-      - name: I will execute
-        if: ${{ failure() }}
-        run: echo "I will print if any previous step fails."
+      - name: Bug step
+        if: ${{ failure() && !cancelled() && contains(github.event.pull_request.title, 'fix') }}
+        run: echo "I am a bug fix "
 
-      - name: I will execute when not cancelled
-        if: ${{ !cancelled() }}
-        run: echo "I will always print, except when the workflow is cancelled."
+      
 
-      - name: I will execute when cancelled
-        if: ${{ cancelled() }}
-        run: echo "I will print if the workflow is cancelled."
+      
+
+      
+        
+      # - name: Failing step
+      #   run: |
+      #     sleep 20
+      #     exit 1
+
+      # - name: I will be skipped
+      #   if: ${{ success() }}
+      #   run: echo "I will print if previous steps succeed."
+
+      # - name: I will execute
+      #   if: ${{ failure() }}
+      #   run: echo "I will print if any previous step fails."
+
+      # - name: I will execute when not cancelled
+      #   if: ${{ !cancelled() }}
+      #   run: echo "I will always print, except when the workflow is cancelled."
+
+      # - name: I will execute when cancelled
+      #   if: ${{ cancelled() }}
+      #   run: echo "I will print if the workflow is cancelled."
